### ISSUE TITLE
Support PSR7Session?

### ISSUE THREAD

**Issue by Ocramius** [oscarotero/psr7-middlewares#10]
Just dropping it here: https://github.com/Ocramius/PSR7Session

Maybe interesting?

Note: requirement is PHP ^7.0 (won't be downgraded)

**Comment by oscarotero** [comment]
I know the project and It's really interesting. The only problem is php7 (this library requires ^5.5 and I'm not sure whether it's a good idea to have different requirements for different middlewares).

**Comment by oscarotero** [comment]
I'm working in the [v4.x](https://github.com/oscarotero/psr7-middlewares/tree/4.x-dev) that requires PHP 7.0+. The aim is to be fully compatible with 3.x but adding other PHP7-only middlewares, like this one.

**Comment by oscarotero** [comment]
Because PSR7Session can work as a middleware itself, there's no need to create an adapter in this package.
So I close this issue.

**Comment by Ocramius** [comment]
Ah, sorry, I probably misinterpreted the scope of this project, thinking that it was aggregating initialization of different middlewares spread across the interwebs.

**Comment by oscarotero** [comment]
There's a way to aggregate new middlewares from a 3rd party libraries, so you can provide an adapter. For example:

``` php
namespace PSR7Session\Middleware;

//Register this namespace that contains more middleware pieces:
\Psr7Middlewares\Middleware::registerNamespace(__NAMESPACE__);

//Define the middleware:
class Psr7Session
{
    // ...
}
```

To use it:

``` php
$middleware[] = Middleware::Psr7Session();
```

If you like it, I can create a pull request.

**Comment by Ocramius** [comment]
Ah, I see, so this would go the other way around. My bad, I really misunderstood how this project works, sorry :D
