### ISSUE TITLE
Middleware request: CSRF Protection

### ISSUE THREAD

**Issue by matthijsthoolen** [oscarotero/psr7-middlewares#13]
Hi!

Thanks for the nice library. I would like to suggest some middlewares, I will make a seperate issue for each request. 

It would be nice to have middleware for CSRF protection. I think the Slim-Csrf has support for psr-7. https://github.com/slimphp/Slim-Csrf

Also, I would like to build some middlewares myself to help expand the support for more middleware. But at this moment I am not sure how to do this exactly. Could you give me some tips?

**Comment by oscarotero** [comment]
Thanks for the suggestion, the CSRF middleware is a good thing!
You're welcome to build more middlewares, just fork this project and create a pull request for each middleware.

**Comment by oscarotero** [comment]
Just one thing: use the `develop` branch (or create your own `feature/*` branch), please.
Thank you :smiley:

**Comment by oscarotero** [comment]
The 3.11 release adds a CSRF middleware. Close this.

**Comment by matthijsthoolen** [comment]
Nice!
