### ISSUE TITLE
Feature request: custom middleware

### ISSUE THREAD

**Issue by matthijsthoolen** [oscarotero/psr7-middlewares#15]
As far as I can see the only way to add middleware is to add it to the middleware folder. 

I thought it would be nice to also add a configuration option to also include middleware from a different custom location. 

This way you can also add middleware from other sources (without struggling with updates/composer). And it's easier to build/change middleware for application specific purposes. 

For example: I would like to have a middleware which will check my database if a user is already connected. I don't think that is interesting for anyone else :)

**Comment by oscarotero** [comment]
Why not simply instantiate your middlewares? I mean:

``` php
$dispatcher = $relay->newInstance([
    Middleware::formatNegotiator(), //middleware from this package
    new CustomMiddleware(), //your own middleware
];
```

**Comment by matthijsthoolen** [comment]
I did not know that that was possible! But that sounds like a good solution for my request. So I will close this issue!

Isn't it a good idea to add this to readme?

**Comment by oscarotero** [comment]
A middleware is just a function inserted in the request/response cycle. It's well explained here: https://mwop.net/blog/2015-01-08-on-http-middleware-and-psr-7.html
This library it's only a collection of them, but you can take more from other packages (https://packagist.org/search/?q=psr-7%20middlewares) or create your own
