### ISSUE TITLE
Https Redirect includes port 80

### ISSUE THREAD

**Issue by adear11** [oscarotero/psr7-middlewares#24]
I'm trying to use Https middleware with a Slim 3 application.

When I attach the middleware to a route, the https redirection is happening, however, the URI that I'm being redirected to is `https://my-dev-site.local:80/rest/of/the/path`.

Now, I know where the 'problem' is, and I have found a seemingly easy fix for it, but I'm not sure of whether the fault lies with the Https middleware or if it is Slim's Psr\Http\Message\UriInterface implementation.

When the new URI is created with the `https` scheme on Line 78 of Https.php, only the scheme of the URI is updated `$uri = $uri->withScheme('https');`. This leave the port of the URI set to its original value of 80. When this newly created URI is cast to a string by the `RedirectResponseTrait`, it generates a URI with a scheme of https and a port of 80. It is happening because the Slim UriInterface implementation compares the scheme and port to see if they are 'standard'. If the scheme is http and the port is 80, it does not include in port the string cast. Likewise, if the scheme is https and the port is 443 a port is not included in the string cast.

In this case, since the scheme is being changed, but not the port, Slim's Uri class is returning the non-standard https port of 80 in the string URI.

The simple solution to this is to update Https middleware to also change the port to 443. So, line 78 of Https.php becomes `$uri = $uri->withScheme('https')->withPort(443)`. 

If this is acceptable, I can do a pull request for this small change, but I wanted to bring it up here first to see if there could be any unforeseen consequences caused by this.

**Comment by oscarotero** [comment]
Hi, @adear11 
Thanks for reporting. I think your solution is perfect. Your pull request is welcome. :+1:

**Comment by oscarotero** [comment]
New [3.13.1](https://github.com/oscarotero/psr7-middlewares/releases/tag/v3.13.1) version released including your fix. :)
