### ISSUE TITLE
Would traits better replace the static class?

### ISSUE THREAD

**Issue by designermonkey** [oscarotero/psr7-middlewares#29]
I am assuming that the Middleware class is basically a collection of functions, which are collected into a class instance?

``` php
$request = Middleware::setAttribute($request, self::KEY, $this->basePath);

// better as

use RequestAttributesHelperTrait;

$request = $this->setRequestAttribute($request, self::KEY, $this->basePath);
```

Using this as an example, it would be (IMO) better to have a set of traits to allow this functionality to be implanted into middlewares, rather than relying on a static class. Obviously backwards compatibility is an issue, so the static class can use the traits and still implement it's own methods.

When it comes to the factory method, I think an abstract factory class would be more apt, which can also have a helper trait to allow injecting itself into middleware instances that require it.

What do you think about an architectural change like this? Being that it is such a large change, it could be argued into a version release, but having a good backwards compatibility, it could be a feature release. I don't mind working on it, as I really like this codebase and want to use it, but I just can't bring myself to allow statics into my codebase :D

**Comment by oscarotero** [comment]
If I understand it correctly, you want to move the methods related with attributes to a trait. I think it can be fine, but there's a global constant used by these methods (`Middleware::KEY`) that should be defined anywhere and it's not possible to define constants in traits.

And about the factory method, can you write some example code?

**Comment by designermonkey** [comment]
I never thought about the `Middleware::KEY` :(

**Comment by oscarotero** [comment]
As you can see, the purpose of this constant is to define the key used to store the array that contains all attributes, in order to avoid conflicts with other middleware pieces.

Because it's a constant, that cannot be modified, two possible solutions come to my mind:
- Use the value directly, instead a constant. For example:
  
  ``` php
  $request->getAttribute('Psr7Middlewares\\Middleware');
  ```
- Use a php magic constant with the same value always, for example `__NAMESPACE__`:
  
  ``` php
  $request->getAttribute(__NAMESPACE__);
  ```

Of course, another solution is leave this as is :)

**Comment by wolfy-j** [comment]
I agree with the idea of making smaller middleware block, can be very useful in more complex filters. Maybe move this constant into separate class? Like Middleware::IP_ADDRESS it will outer dependency but traits from the same package.

**Comment by designermonkey** [comment]
The idea I have is to lead to being able to allow third party middleware to be used by the same system, and extend your ideas by using the traits I'm on about; It wouldn't just be an attribute trait, but the other parts as well. Because of this the `__NAMESPACE__` would probably be a bad idea. A private property perhaps?

The factory I had in mind would be a class containing an array of name => namespaced classdefinitions that would be used to create the middlewares from.. This would allow others to add their own to the factory too.

It's all just an idea, and I don't mind if it's rejected. I always feel uneasy about static calls though, that's all.

**Comment by oscarotero** [comment]
A private property is another option. It can be changeable by the middleware but that can be a feature (allow to create different namespaces).

If you feel strong with this idea, you can create a pull request and continue the discussion with some code in sight :)

**Comment by oscarotero** [comment]
Hi. I've implemented this in the new version (3.14)

There's the `AttributeTrait` to save attributes. It continue to rely on the static class due the constant KEY but, at least it is easy to create new middleware importing only traits and not other static things.
There's also the method `Middleware::registerNamespace()` to add other vendor namespaces to the factory.

**Comment by designermonkey** [comment]
Thanks! Sorry I didn't get any time to have a try at this. Clients have taken over my life recently.

**Comment by oscarotero** [comment]
No worries :)
