### ISSUE TITLE
FielTrait::getFilename ignores query parameters

### ISSUE THREAD

**Issue by Anahkiasen** [oscarotero/psr7-middlewares#4]
Currently a page is cache only depending on its URI path, ignoring all query parameters. Which means if you have per examples query parameters to sort a table, or switch tabs, they all serve the same cached page.

**Comment by oscarotero** [comment]
Hello. What are your use case?
This method is used in `Middleware::readResponse()` and `Middleware::saveResponse()`.
In saveResponse the page is saved only if no query parameters are in the url (https://github.com/oscarotero/psr7-middlewares/blob/master/src/Middleware/SaveResponse.php#L31)
ReadResponse does not check whether there's query parameters in the url. These two middlewares are designed to create a basic file based cache, for static pages, so query parameters are not covered.
Maybe this the problem?

**Comment by Anahkiasen** [comment]
My use case is filtering a timeline, so I have "tabs" of sorts that display different content. I think indeed it's caching the page when there's no query parameter (view all) but then that cache is reused when there _are_ query parameters.

**Comment by oscarotero** [comment]
To do that, you need to use `Cache`, combined with any psr6 compliance library. In the tests I'm using http://www.scrapbook.cash/ that have adapters for many storage systems including filesystem (using flysystem). An example:

``` php
// create Flysystem object
$adapter = new \League\Flysystem\Adapter\Local('/path/to/cache', LOCK_EX);
$filesystem = new \League\Flysystem\Filesystem($adapter);

// create Scrapbook cache object
$cache = new \MatthiasMullie\Scrapbook\Adapters\Flysystem($filesystem);

// create a psr6 Pool object from cache engine
$pool = new \MatthiasMullie\Scrapbook\Psr6\Pool($cache);

//middlewares
$dispatcher = $relay->newInstance([
    Middleware::cache($pool)
]);
```
