### ISSUE TITLE
Custom Middleware

### ISSUE THREAD

**Issue by undercloud** [oscarotero/psr7-middlewares#45]
Can I create my own middleware like this?

``` PHP
class MiddlewareMy extends MiddlewareBase
{
    public function handle(...) 
    {

    } 
}
```

**Comment by oscarotero** [comment]
I'm not sure what do you mean with "Custom middleware". Of course, you can create any middleware, there's no a `MiddlewareBase`, just need to create a class with the signature:

``` php
class MiddlewareMy
{
    public function __invoke(RequestInterface $request, ResponseInterface $response, callable $next)
    {
    }
}
```

This project is just a collection of middleware classes with this signature.

**Comment by undercloud** [comment]
ok)
