### ISSUE TITLE
Slim v3 and DigestAuth middleware is endlessly looping the password dialog.

### ISSUE THREAD

**Issue by martisj** [oscarotero/psr7-middlewares#67]
I am using it like this
```php
use Psr7Middlewares\Middleware;

$app->group('/api', function () use ($app) {
    $app->get('/ping', function () {...});
})->add(
    Middleware::DigestAuthentication(['me' => 'andYou'])
);
```

**Comment by padjon** [comment]
adding this to my .htaccess did the trick for me:
`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

**Comment by oscarotero** [comment]
It seems to be an issue with the Http library. I don't have this problem with diactoros.

**Comment by martisj** [comment]
@padjon Seems like that works, I don't have a clue why though 😕
