### ISSUE TITLE
MiddlewareInterface

### ISSUE THREAD

**Issue by Ngob** [oscarotero/psr7-middlewares#72]
Hello,

I noticed your middleware is not compatible with Interop\Http\ServerMiddleware\MiddlewareInterface.
Will you upgrade your package?

Thanks,
Best regards,

**Comment by oscarotero** [comment]
Yes, the PSR-15 version is here: https://github.com/middlewares/psr15-middlewares

**Comment by Ngob** [comment]
Thanks you very much :)
