### ISSUE TITLE
https middleware

### ISSUE THREAD

**Issue by jimblue** [oscarotero/psr7-middlewares#73]
Hello,

Actually it's not possible to activate or deactivate **https middleware** by passing an argument like for **www middleware** does :

`Middleware::Www(true)`

This is really useful when switching from a development to production environment.

Is it possible to add this function?

Thank you so much.

**Comment by oscarotero** [comment]
That's good idea. I'm implementing this 👍

**Comment by jimblue** [comment]
Great ! :)

**Comment by oscarotero** [comment]
I've commited a fix for this. Can you check if it works fine?
Thanks

**Comment by jimblue** [comment]
That's rock 😄  !

You can definitely make the release for composer hehe

Thank you so much @oscarotero

**Comment by danizord** [comment]
Hey everyone, what about using composition for that?

`Middleware::Toggle(Middleware::Www(), true)`
`Middleware::Toggle(Middleware::Https(), false)`

**Comment by jimblue** [comment]
Hi! 

I'm using it like this and that work well: Middleware::Www(true)

Why do you want an other way to switch on/off ?

**Comment by danizord** [comment]
Because it would work out of the box for any PSR-15 compatible middleware
without the need to add this constructor argument.

**Comment by jimblue** [comment]
OK :)

**Comment by oscarotero** [comment]
3.20 released

**Comment by jimblue** [comment]
@oscarotero thanks
