### ISSUE TITLE
Firewall middleware needs ClientIp executed before

### ISSUE THREAD

**Issue by babeuloula** [oscarotero/psr7-middlewares#89]
Hello, 

I use Slim3 and I try to use the firewall but I've an error : 

```php
use Psr7Middlewares\Middleware;

// Firewall
$app->add(Middleware::ClientIp());
$app->add(Middleware::Firewall(['37.97.90.193']));
```

ClientIp has launch before Firewall. Why I've this error ?

Thanks

**Comment by oscarotero** [comment]
What error is throwed?

**Comment by babeuloula** [comment]
This is the subjet of the topic : `Firewall middleware needs ClientIp executed before`

File: .../psr7-middlewares/src/Middleware/Firewall.php:76

**Comment by oscarotero** [comment]
I don't see why are you getting this error, but suspect it's something unrelated with this package.
Are you sue that ClientIp is executed before Firewall, and the request passed to Firewall has the request attribute with the ClientIp data?

**Comment by babeuloula** [comment]
Of course ClientIp is launch before.
As you can see I execute ClientIp before Firewall : 

```php
$app->add(Middleware::ClientIp());
$app->add(Middleware::Firewall(['37.97.90.193']));
```

If you read the [documentation](https://www.slimframework.com/docs/concepts/middleware.html) of Slim3, you register middleware like this `$app->add( new ExampleMiddleware());`

**Comment by oscarotero** [comment]
I just installed and try slim and works fine. The problem is you're adding the middlewares in reverse order. Slim insert the middlewares at the begining of the stack so in your example firewall is executed before clientIp.

The opposite order should work fine:

```php
$app->add(Middleware::Firewall(['37.97.90.193']));
$app->add(Middleware::ClientIp());
```

**Comment by danopz** [comment]
@babeuloula this behavior is descibed here: https://www.slimframework.com/docs/concepts/middleware.html#how-does-middleware-work

**Comment by babeuloula** [comment]
@oscarotero Ok I will test this tomorrow. Thanks
