### ISSUE TITLE
Use statement for RuntimeException required in class ContainerTrait  

### ISSUE THREAD

**Issue by hwmaier** [oscarotero/psr7-middlewares#9]
A use statement needs to be added to class `ContainerTrait` for the `RuntimeException` like shown below:

```
<?php

namespace Psr7Middlewares\Utils;

use Interop\Container\ContainerInterface;
use InvalidArgumentException;
use RuntimeException;
```

otherwise the `RunTimeException` class will not be found when thrown as it is looked up in local namespace.

**Comment by oscarotero** [comment]
Good catch! Fixed in the new version.
thank you
